[features]
seeds = false
[programs.localnet]
signatures = "6eX3sxexs8Ct67xdxjjGJ4HLybK7YR6QkcWmaMhwgTcS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
eth_sign = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/eth_signatures.ts"
eth_recovery = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/eth_recovery.ts"
